{% set version = "0.2.0" %}
{% set sha256 = "9ceacc50decd3ea3005e7ea9480bb22040075756ba3f1c6e7f411fe34c2b1f98" %}

package:
  name: pyfive
  version: {{ version }}

source:
  fn: pyfive-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pyfive/pyfive-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy

test:
  imports:
    - pyfive

about:
  home: https://github.com/jjhelmus/pyfive
  license: BSD 3-Clause
  summary: 'A pure Python HDF5 file reader'

extra:
  recipe-maintainers:
    - jjhelmus
