{% set name = "pyfive" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyfive-{{ version }}.tar.gz
  sha256: 0ff913e0dc9a26c1bcbe28887f7a30ef9de95330054d868491c510ee288f817e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy

test:
  imports:
    - pyfive
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jjhelmus/pyfive
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'A pure Python HDF5 file reader'

extra:
  recipe-maintainers:
    - valeriupredoi
    - jjhelmus
