{% set name = "pyfive" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyfive-{{ version }}.tar.gz
  sha256: 17d33cfa5e8c639023f16cc2bbb7ebd10f2c645e2c9aee86eb6d7bafb2bd410c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy

test:
  imports:
    - pyfive
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jjhelmus/pyfive
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'A pure Python HDF5 file reader'

extra:
  recipe-maintainers:
    - davidhassell
    - valeriupredoi
    - jjhelmus
