travis:
  secure:
    BINSTAR_TOKEN: hPPaGueS5+h6k++RkUAslsGWoqdJO7Gir5LxVWD9bu3d2rfMFXyEFYWcQnpb5Q2TBEc6AUnm/4DvquVeOBvuhO/wkYrDdCOFnLtWk3QcdMA5j37dVIVMzL31HK3Bw3jQ7A/XiPdKTbIQxAdfgJgN8g5radZebCSMkY74TGhw4MP09Msyqb8fgY7/OR7ufBbiMFY2YcwbYqMU7HMFv0zwHDoA6wopHKGS1F6G4fta4kGm34YB5rMBkyB0FFQ/HyD80c27f+rkfA2zIQnF8F4NGu6QtwUYE8MZz6FyHwFzmqiNs+ktEfCumPu6v8lT+XaP1NWJ6OtVco2sfErgo2e2kCDRqi18rw8yEwCCv6XBXEKm2Ra8y5ioI24DoDZpXZkmbqxWKsHR6kIBukJ1QfYciM4kcALq0E49rTfsdu56w85yarOFCRgoEfZIkgRcODVZXwShwbeOwyw6k6YAQTf24Q0ndp55An4JQkGvKPqnrlUTGkV8eM7iLJPCBgJK360NAUsoQ1zwzassDz7/QTZ7rqLIPCcMyjlHkr6q3og6CH7Rf8aOYmCP/9aFDTxO8GPaciip9veG69y8RHgE9hw+YRjic+XqUKdcJtFntUF+XQtNLr5nAfDtq+aQHPSkrUEpXesIw43HhSoJa7brrEka8dKyQCkIgu0sxdlQ5jgmgkU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
