travis:
  secure:
    BINSTAR_TOKEN: bGLUv9REadhvdFdRSVI3FEkEJ2/IcI1dKc2kAIv6gFi/Kt/P0nbU2GzDRxQ2RqGvsDL1zdd6N/Oa6DTPBx48ljflHlYlmWfJgFqePUeLKAgwyqL3VTtAuXnnZDBu5fUHA3KEQyZ+/VuYoMMcW0UTJc7wubkbyxAnMvXza9VIsIwRIwXaM0IH0iYPQK4ixeKuGRZAg/iKCBkxksLQenjBiGDkyJKEbJK2YLyIUw6a6nrlgSFVcxmXygAsxBPace1sSdjX05KvlXz9jKOFM7mUnvpAHWTCTygD1AhkCVFiPlgNJ7awI7UNdJd5vPdAxRp2jKN/7VBqui10gy3vsvbLVfqUwD8CNQpr1XBuLkSPuH8NK5GsugMOpViutvQYLsYLcwD8V/iVNEi4NgqC/tSaQR0Ew4b4aPkVQgGPipVDCroLsfRrkv1v2OPonre2s4WfnfvynwiBtgYxVCSx6Rj8WaZ70VSXjY1s9W5UVFpX2oHd8UKs81z1YEXHIE8uThF6Ygz1dhj28DCsytq5mVQY/s4jW+y9UxivjQQBL/Y9Va6zrJEjnpQzMkt/KQ4WJyXK/DL7+Th4MbaY/p8mN8tnSKXMGf46uZEIR+nPJ1MTFxJD1toWwuPr2aldfSyQ4V4ysIqU4Kkn/8vO2hPhPXCg4kRJvOKVZDKQoLwyTxmLJ1o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
